name: Archive Latest Amateur Radio Test Banks

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight UTC
  workflow_dispatch:

permissions:
  contents: write

# Note: the jobs depend on each other one after the other.
# This ensures that they are run sequentially. Otherwise a race condition could
# occur where the repository may be updated by one job while another job is
# running.
jobs:
  archive_amateur_advanced_pdf:
    uses: ./.github/workflows/download-and-archive-file.yml
    with:
      remote_endpoint: "http://apc-cap.ic.gc.ca/datafiles/amateur_advanced_questions_en.PDF"
      file_path: "amateur_advanced/pdf/"
      file_extension: ".pdf"

  archive_amateur_basic_pdf:
    needs: archive_amateur_advanced_pdf
    uses: ./.github/workflows/download-and-archive-file.yml
    with:
      remote_endpoint: "http://apc-cap.ic.gc.ca/datafiles/amateur_basic_questions_en.PDF"
      file_path: "amateur_basic/pdf/"
      file_extension: ".pdf"

  archive_amateur_advanced_zip:
    needs: archive_amateur_basic_pdf
    uses: ./.github/workflows/download-and-archive-file.yml
    with:
      remote_endpoint: "https://apc-cap.ic.gc.ca/datafiles/amat_adv_quest.zip"
      file_path: "amateur_advanced/txt/"
      file_extension: ".zip"
      should_extract: true

  archive_amateur_basic_zip:
    needs: archive_amateur_advanced_zip
    uses: ./.github/workflows/download-and-archive-file.yml
    with:
      remote_endpoint: "https://apc-cap.ic.gc.ca/datafiles/amat_basic_quest.zip"
      file_path: "amateur_basic/txt/"
      file_extension: ".zip"
      should_extract: true
