name: Archive Latest Amateur Radio Test Banks

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  archive_amateur_advanced_pdf:
    uses: ./.github/workflows/download-and-archive-file.yml
    with:
      remote_endpoint: "http://apc-cap.ic.gc.ca/datafiles/amateur_advanced_questions_en.PDF"
      file_path: "amateur_advanced"
      file_extension: ".pdf"

  archive_amateur_basic_pdf:
    uses: ./.github/workflows/download-and-archive-file.yml
    with:
      remote_endpoint: "http://apc-cap.ic.gc.ca/datafiles/amateur_basic_questions_en.PDF"
      file_path: "amateur_basic"
      file_extension: ".pdf"

  archive_amateur_basic_zip:
    uses: ./.github/workflows/download-and-archive-file.yml
    with:
      remote_endpoint: "https://apc-cap.ic.gc.ca/datafiles/amat_basic_quest.zip"
      file_path: "amat_basic"
      file_extension: ".zip"

  archive_amateur_advanced_zip:
    uses: ./.github/workflows/download-and-archive-file.yml
    with:
      remote_endpoint: "https://apc-cap.ic.gc.ca/datafiles/amat_adv_quest.zip"
      file_path: "amat_advanced"
      file_extension: ".zip"
