name: Download and Archive File

on:
  workflow_call:
    inputs:
      remote_endpoint:
        description: "The remote file URL to download"
        required: true
        type: string
      file_path:
        description: "The name to use for the subdirectory"
        required: true
        type: string
      file_extension:
        description: "The extension for the downloaded file"
        required: true
        type: string

jobs:
  download_and_archive_file:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set file_name
        run: |
          current_date=$(date --iso-8601)

          # In GitHub actions tr keeps reading forever, and so us dd to limit
          # the input to 512 bytes. The LC_ALL=C is to ensure that the output
          randomized_suffix=$(dd bs=512 if=/dev/urandom count=1 2>/dev/null | LC_ALL=C tr -dc "a-zA-Z0-9" | head -c 10)

          file_name="${current_date}_${randomized_suffix}${{ inputs.file_extension }}"
          echo "file_name=$file_name" >> $GITHUB_ENV

      - name: Download remote file into subdirectory
        run: |
          user_agent="GilanisTestBankArchiver/1.0 (+https://github.com/amingilani/canada-amateur-radio-test-bank-archive)"
          mkdir -p "${{ inputs.file_path }}"
          echo "Downloading from ${{ inputs.remote_endpoint }} to ${{ inputs.file_path }}/${file_name} with User-Agent: ${user_agent}"
          wget --user-agent="${user_agent}" \
              --output-document="${{ inputs.file_path }}/${file_name}" \
              ${{ inputs.remote_endpoint }} || { echo "Download failed!"; exit 1; }

      - name: Generate and store BSD-style SHA-512 checksum
        run: |
          sha512sum --tag "${{ inputs.file_path }}/${file_name}" > "${{ inputs.file_path }}/${file_name}.sha512"

      - name: Copy to latest${{inputs.file_extension}} and latest${{inputs.file_extension}}.sha512
        run: |
          cp "${{ inputs.file_path }}/${file_name}" "${{ inputs.file_path }}/latest${{ inputs.file_extension }}"
          cp "${{ inputs.file_path }}/${file_name}.sha512" "${{ inputs.file_path }}/latest${{ inputs.file_extension }}.sha512"

      - name: Set commit message
        id: set_commit_message
        run: |
          commit_message="Archiving latest ${{ inputs.file_path }}/${file_name}"
          echo "commit_message=$commit_message" >> $GITHUB_OUTPUT

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: ${{ steps.set_commit_message.outputs.commit_message }}
          branch: main
          commit_user_name: Archival Job
          commit_user_email: 2662370B.github.action@gilani.me
